name: nlu_hw
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=2.0.1
  - ipykernel
  - pytorch
  - torchvision
  - transformers
  - accelerate
  - pip
  - pip:
      - datasets
      - evaluate
      - optuna